Update README, appsettings example and pipeline

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -2,13 +2,9 @@ trigger:
   batch: true
   branches:
     include:
-      - main
-      - release/*
+      - "*"
 
-pr:
-  branches:
-    include:
-      - main
+pr: none
 
 pool:
   vmImage: 'ubuntu-latest'
@@ -17,13 +13,13 @@ name: $(Build.BuildId)
 
 variables:
   buildConfiguration: 'release'
-  # .NET SDK version number
+  #.NET SDK version number
   dotnetVersion: '8.0'
-  # PDS custom NuGet feed id
+  #PDS custom NuGet feed id
   nugetFeed: '9fd46a3f-eada-41dc-86e9-36332aeb8ef1/ecd5af68-0566-42db-8cd7-e71176254aa2'
-  # Path of project to be published
+  #Path of project to be published
   publishProjectPath: 'FundingApi/PDS.ViewYourFunding.Data.Api.csproj'
-  # Docker variables
+  #Docker variables
   dockerRegistryServiceConnectionDev: PDS-DEV-ACR
   dockerRegistryServiceConnectionPreProd: PDS-OAT-ACR
   dockerRegistryServiceConnectionProd: PDS-Release-ACR
@@ -33,21 +29,22 @@ variables:
   patToken: $(System.AccessToken)
 
 stages:
-
-# Stage 1 - Audit
+#Stage 1 - Audit stage: This stage checks project dependencies for security vulnerabilities
 - stage: Audit
   displayName: 'Run audit activities'
   condition: always()
   jobs:
+  #Job 1 - Audit: This job checks project dependencies for secuirty vulnerabilites using default dotnet command 
   - job: Audit
-    displayName: 'Audit project dependencies for security vulnerabilities'
+    displayName: 'Audit project dependencies for security vulnerabilites'
     steps:
+    # Step 1 - Set up .NET SDK
     - task: UseDotNet@2
       displayName: 'Set up .NET SDK (version $(dotnetVersion))'
       inputs:
         packageType: 'sdk'
         version: '$(dotnetVersion).x'
-
+    #Step 2 - Restore NuGet packages
     - task: DotNetCoreCLI@2
       displayName: 'Restore .NET project dependencies (NuGet)'
       inputs:
@@ -55,38 +52,43 @@ stages:
         projects: '**/*.csproj'
         feedsToUse: 'select'
         vstsFeed: $(nugetFeed)
-
+    #Step 3 - Check for security vulnerabilities within project dependencies
     - task: Bash@3
       displayName: 'Scan for vulnerable NuGet packages'
       inputs:
         targetType: 'inline'
         script: |
+          # Run dotnet command to check for vulnerable packages, including transitive dependencies
           dotnet list package --vulnerable --include-transitive 2>&1 | tee build.log
           echo "Analyse dotnet list package command log output..."
+          #TODO - when we find an alternative to AutoMapper, change back to including high severity vulnerabilities in the scan.
+          # if grep -q -i "critical\|high" build.log; then
           if grep -q -i "critical" build.log; then
-              echo "Must fix critical security vulnerabilities."
-              exit 1
+              echo "Must fix security vulnerabilities found on the log output."
+              exit 1      # Fails the job if critical or high vulnerabilities are found
           else
-              echo "No critical vulnerabilities found."
-              exit 0
+              echo "No critical or high severity vulnerabilities found."
+              exit 0      # Passes the job if no critical/high vulnerabilities are found
           fi
 
-# Stage 2 - Test
+  #Stage 2 - Test stage: This stage runs the project unit tests
 - stage: Test
   displayName: 'Run unit tests'
   dependsOn: Audit
   condition: succeeded()
   jobs:
+  #Job 1 - Unit: Runs unit tests.
   - job: Unit
     displayName: 'Run unit tests'
     dependsOn: []
     steps:
+    # Step 1 - Set up .NET SDK
     - task: UseDotNet@2
       displayName: 'Set up .NET SDK (version $(dotnetVersion))'
       inputs:
         packageType: 'sdk'
         version: '$(dotnetVersion).x'
-
+    #Step 2 - Restore NuGet packages
     - task: DotNetCoreCLI@2
       displayName: 'Restore .NET project dependencies (NuGet)'
       inputs:
@@ -95,14 +97,14 @@ stages:
         feedsToUse: 'select'
         vstsFeed: $(nugetFeed)
         verbosityRestore: 'Normal'
-
+    # Step 3 - Build the project
     - task: DotNetCoreCLI@2
       displayName: 'Build project'
       inputs:
         command: 'build'
         projects: '**/*.csproj'
         arguments: '--configuration $(buildConfiguration) --no-restore'
-
+    # Step 4 - Run unit tests and filter by category
     - task: DotNetCoreCLI@2
       displayName: 'Run unit tests'
       inputs:
@@ -111,18 +113,18 @@ stages:
         arguments: '--configuration $(buildConfiguration) --no-build --collect "Code coverage" --filter TestCategory=Unit'
         testRunTitle: '$(Build.Repository.Name)-Unit-$(Build.BuildId)'
 
-# Stage 3 - Publish
+#Stage 3 - Publish stage: This stage publishes the Docker Image and build artifact to be deployed in the release pipelines
 - stage: Publish
   displayName: 'Publish Docker image and build artifact'
   dependsOn: Test
   condition: succeeded()
   jobs:
-
-  # Dev build (now using MAIN branch)
+  # Job 1 - Build and Push to Development ACR
   - job: DockerBuildDev
     displayName: 'Build and push Docker image for Development'
-    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
+    condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
     steps:
+    # Step 1: Build the Docker image
     - task: Docker@2
       displayName: 'Build Docker image'
       inputs:
@@ -136,7 +138,7 @@ stages:
           $(tag)
         arguments: |
           --build-arg PDS_FEED_PAT=$(patToken)
-
+    # Step 2: Push the Docker image to the Development container registry
     - task: Docker@2
       displayName: 'Push Docker image to Development container registry'
       inputs:
@@ -146,14 +148,14 @@ stages:
         tags: |
           latest
           $(tag)
-
-  # Release builds
+  # Job 2 - Build and Push to Pre-production and Production ACR
   - job: DockerBuildPreProdProd
     displayName: 'Build and push Docker Image for Pre-production and Production'
-    condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/release')
+    condition: startsWith(variables['build.sourceBranch'], 'refs/heads/release')
     steps:
+    # Step 1: Build the Docker image
     - task: Docker@2
-      displayName: 'Build Docker image (PreProd)'
+      displayName: 'Build Docker image'
       inputs:
         command: build
         repository: $(imageRepository)
@@ -162,11 +164,11 @@ stages:
         tags: |
           latest-rc
           $(tag)-rc
-        arguments: |
+        arguments:
           --build-arg PDS_FEED_PAT=$(patToken)
-
+    # Step 2: Push the Docker image to the Pre-prod container registry
     - task: Docker@2
-      displayName: 'Push Docker image to Pre-prod'
+      displayName: 'Push Docker image to Pre-prod container registry'
       inputs:
         command: push
         repository: $(imageRepository)
@@ -174,9 +176,9 @@ stages:
         tags: |
           latest-rc
           $(tag)-rc
-
+    # Step 3: Build the Docker image
     - task: Docker@2
-      displayName: 'Build Docker image (Prod)'
+      displayName: 'Build Docker image'
       inputs:
         command: build
         repository: $(imageRepository)
@@ -185,11 +187,11 @@ stages:
         tags: |
           latest-rc
           $(tag)-rc
-        arguments: |
+        arguments:
           --build-arg PDS_FEED_PAT=$(patToken)
-
+    # Step 4: Push the Docker image to the Prod container registry
     - task: Docker@2
-      displayName: 'Push Docker image to Prod'
+      displayName: 'Push Docker image to Prod container registry'
       inputs:
         command: push
         repository: $(imageRepository)
@@ -197,17 +199,17 @@ stages:
         tags: |
           latest-rc
           $(tag)-rc
-
-  # Artifact publishing
+  # Job 3 - Publish: This job publishes the build artifact from the project
   - job: PublishArtifact
     displayName: 'Publish build artifact'
     steps:
+    # Step 1 - Set up .NET SDK
     - task: UseDotNet@2
       displayName: 'Set up .NET SDK (version $(dotnetVersion))'
       inputs:
         packageType: 'sdk'
         version: '$(dotnetVersion).x'
-
+    #Step 2 - Restore NuGet packages
     - task: DotNetCoreCLI@2
       displayName: 'Restore .NET project dependencies (NuGet)'
       inputs:
@@ -215,14 +217,15 @@ stages:
         projects: '**/*.csproj'
         feedsToUse: 'select'
         vstsFeed: $(nugetFeed)
-
+        verbosityRestore: 'Normal'
+    # Step 3 - Build the project
     - task: DotNetCoreCLI@2
       displayName: 'Build project'
       inputs:
         command: 'build'
         projects: '**/*.csproj'
         arguments: '--configuration $(buildConfiguration) --no-restore'
-
+    #Step 4 - Publish project
     - task: DotNetCoreCLI@2
       displayName: 'Publish project'
       inputs:
@@ -231,7 +234,7 @@ stages:
         zipAfterPublish: true
         projects: $(publishProjectPath)
         arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'
-
+    #Step 5 - Publish tests for release pipelines
     - task: DotNetCoreCLI@2
       displayName: 'Publish tests'
       inputs:
@@ -240,14 +243,14 @@ stages:
         zipAfterPublish: false
         projects: Tests/PDS.ViewYourFunding.Data.Tests.csproj
         arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build'
-
+    #Step 6 - Copy published project to artifact directory
     - task: CopyFiles@2
-      displayName: 'Copy files to artifact directory'
+      displayName: 'Copy files to: $(build.artifactstagingdirectory)'
       inputs:
         contents: |
           azure/**
         targetFolder: '$(build.artifactstagingdirectory)/publish'
-
+    #Step 7 - Publish build artifact
     - task: PublishBuildArtifacts@1
       displayName: 'Publish build artifact'
       inputs:
